const {run}=require('./browser.cjs'),assert=require('node:assert/strict'),fs=require('fs');
run(async browser=>{
 const ctx=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{errors.push(d.message());d.dismiss()});
 await page.goto('http://localhost:8765');await page.waitForFunction(()=>window.ParadasCatalog?.current&&typeof state!=='undefined');await page.waitForTimeout(600);
 const pilot=await page.evaluate(()=>PARADA_ID);
 await page.evaluate(async()=>{await otsCollection().doc('4881375').set({supervisorA:'Conservar piloto'},{merge:true})});
 const pkg=await page.evaluate(async()=>{const zip=new JSZip();zip.file('parada.json',JSON.stringify({format:'paradas-bradson-package',version:1,id:'qa-parada',name:'Parada QA',definition:JSON.parse(JSON.stringify(SEED_DATA)),brand:BRANDING}));zip.file('plantilla.docx',await(await fetch('./assets/plantilla-informe.docx')).arrayBuffer());return await zip.generateAsync({type:'base64'})});
 await page.locator('#btnMenuMantenciones').click();await page.locator('#paradaZip').setInputFiles({name:'parada.zip',mimeType:'application/zip',buffer:Buffer.from(pkg,'base64')});await page.waitForFunction(()=>window.ParadasCatalog?.current?.id==='qa-parada');await page.waitForTimeout(700);
 assert.equal(await page.evaluate(()=>state.liveOtSupervisor['4881375']?.A),undefined);
 await page.evaluate(async()=>{await otsCollection().doc('4881375').set({supervisorA:'Nueva parada'},{merge:true})});
 const backup=await page.evaluate(async()=>{const blob=await ParadasLocal.exportBackup();return new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(blob)})});
 const fresh=await browser.newContext();const p2=await fresh.newPage();await p2.goto('http://localhost:8765');await p2.waitForFunction(()=>window.ParadasCatalog?.current);await p2.evaluate(async b=>{await ParadasLocal.restoreBackup(await ParadasLocal.readBackup(await(await fetch(b)).blob()))},backup);await p2.reload();await p2.waitForFunction(()=>window.ParadasCatalog?.current?.id==='qa-parada');await p2.waitForTimeout(700);assert.equal(await p2.evaluate(()=>ParadasCatalog.rows.length),2);assert.equal(await p2.evaluate(()=>state.liveOtSupervisor['4881375'].A),'Nueva parada');await p2.locator('#btnMenuMantenciones').click();await p2.locator(`[data-parada="${pilot}"]`).click();await p2.waitForFunction(id=>window.ParadasCatalog?.current?.id===id,pilot);await p2.waitForTimeout(700);assert.equal(await p2.evaluate(()=>state.liveOtSupervisor['4881375'].A),'Conservar piloto');await fresh.close();
 console.log('PASS Importación ZIP, aislamiento y restauración del catálogo en perfil nuevo');
 await page.locator('#workspaceNav button[data-route="informes"]').click();await page.locator('#btnCrearInformeVista').click();await page.locator('#informeNumero').fill('QA210');await page.locator('#informeTituloGeneral').fill('Informe de validación');await page.locator('.informe-ot-check[data-ot="4881375"]').check();await page.locator('#informeSave').click();await page.waitForFunction(()=>state.informes.length===1);await page.locator('[data-abririnforme] .informe-card-nombre').click();await page.waitForTimeout(600);await page.locator('#btnEditarComoDocumento').click();await page.waitForSelector('#vistaInteractivaContenedor section.docx-preview',{timeout:60000});await page.waitForTimeout(1000);
 assert.equal(await page.locator('.editor-herramientas').count(),0);const bounds=await page.evaluate(()=>['vistaInteractivaCerrar','editorTitulo','editorBtnWord','editorBtnPdf'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return {id,x:r.x,y:r.y,w:r.width,h:r.height}}));assert(Math.max(...bounds.map(r=>r.y+r.h/2))-Math.min(...bounds.map(r=>r.y+r.h/2))<3);assert(bounds.every(r=>r.x>=0&&r.x+r.w<=390));
 const dimensions=await page.locator('#vistaInteractivaContenedor section.docx-preview').first().evaluate(el=>({width:el.offsetWidth,height:el.offsetHeight}));console.log('PAGE',dimensions);
 const chooser=page.waitForEvent('filechooser');await page.locator('.doc-firma-control').first().click();await(await chooser).setFiles({name:'firma.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l8AAAAASUVORK5CYII=','base64')});await page.waitForFunction(()=>!!state.informeActivo.encargadoFirmaUrl);await page.waitForTimeout(1800);await page.screenshot({path:__dirname+'/editor-2.1.0-mobile.png'});
 assert.equal(await page.locator('#editorBtnPdf, #btnGenerarPdfInforme, [data-pdfinforme]').count(),0);console.log('PASS el informe ya no ofrece PDF');const signature=await page.evaluate(async()=>({url:state.informeActivo.encargadoFirmaUrl,size:(await(await fetch(state.informeActivo.encargadoFirmaUrl)).blob()).size}));assert(signature.size>0);await page.reload();await page.waitForFunction(()=>state.informes?.length===1);assert.equal(await page.evaluate(()=>state.informes[0].encargadoFirmaUrl),signature.url);assert.deepEqual(errors,[]);
 fs.writeFileSync(__dirname+'/results-2.1.0.json',JSON.stringify({checks:['package import','separate parada data','restore fresh profile catalog and active parada','pilot data preserved','single-row mobile header','signature upload and reload'],dimensions,bounds,errors},null,2));await ctx.close();console.log('PASS Encabezado móvil y firma persistente');
}).catch(e=>{console.error(e);process.exitCode=1});






